
Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    # vb.name = "my_centos"
    vb.linked_clone = true
    vb.memory = "1024"
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network :private_network, ip: "192.168.60.#{i + 10}"
    end
  end
  
end
